name: kubectl-validate
on:
  pull_request:
    branches:
      - main
  
env:
  MANIFESTS_PATH: '*thing.yaml'
  
jobs:
  k8sManifestsValidation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install kubectl-validate
        run: go install sigs.k8s.io/kubectl-validate@latest
        
      - name: Run kubectl-validate
        shell: bash
        run: kubectl-validate $MANIFESTS_PATH --version 1.23
        
#       - name: Report status
#         if: failure()
#         run: exit 1
