name: kubectl-validate

on:
  pull_request:
    branches:  
      - main

env:
  MANIFESTS_PATH: 'k8s-manifests/*.yaml'

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:

          - name: checkout repo content
            uses: actions/checkout@v3

          - name: Setup go
          - uses: actions/setup-go@v4
            with:
              go-version: '1.20'
              
          - name: Install kubectl-validate
            run: go install sigs.k8s.io/kubectl-validate@latest

          - name: run kubectl-validate
            run: /go/bin/kubectl-validate "$MANIFESTS_PATH" --version 1.23
