# |======================== Datree Policy Check ==================================|
# | This workflow will verify that every committed yaml files are valid.          |
# | For more info visit: https://github.com/marketplace/datree                    |
# |===============================================================================|

name: Datree Workflow

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  configs-validation:
    runs-on: ubuntu-latest
    env:
      DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            *.yaml
            *.yml
      - name: List all changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Install Datree's CLI
        if: steps.changed-files.outputs.any_changed == 'true'
        run: curl https://get.datree.io | /bin/bash -s

      - name: Datree validate YAML files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: datree validate-yaml ${{ steps.changed-files.outputs.all_changed_files }}
        
# |======================== Datree Policy Check ==================================|
# | Enable this step if you would like to preform K8s policy check on your files. |
# | For more info visit: https://github.com/datreeio/datree                       |
# |===============================================================================|

      - name: Datree validate K8s manifests
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: datreeio/action-datree@main
        with:
          path: ${{ steps.changed-files.outputs.all_changed_files }}
