name: Datree YAML Validation

on:
  pull_request:
    branches: [$default-branch]

jobs:
  YamlValidation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            *.yaml
            *.yml

      - name: List all changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Install datree.io
        if: steps.changed-files.outputs.any_changed == 'true'
        run: curl https://get.datree.io | /bin/bash -s

      - name: Datree Validate yaml
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        run: datree test --validate-yaml ${{ steps.changed-files.outputs.all_changed_files }}
